version: '3'

services:
  upm-db:
    build:
      context: .
      dockerfile: Dockerfile-upm-db
    volumes:
      - upm-db-data:/var/lib/mysql
    container_name: "upm-db"
    env_file: ./docker-configs/upm-db.env
    restart: always
  upm-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - upm-db
    links:
      - upm-db:mysql-server
    container_name: "upm-server"
    ports:
      - 1616:1616
      - 1717:1717
volumes:
  upm-db-data:
